server:
  port: 9096

spring:
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service

jwt:
  secretKey: ${ssa_secretkey}
  issuer: ${ssa_issuer}
  audience: ${ssa_audience}

rabbitmq:
  #EXCHANGE
  elastic-exchange: elasticExchange
  #PRODUCER

  #CONSUMER
  elastic-save-queue: elasticSaveQueue

redis:
  host: localhost
  port: 6379

#logging:
#  level:
#    root: debug
#  file:
#    name: elastic.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB #1mb asilirsa sikistirip yeni dosya olusturacak