server:
  port: 9095

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${sma_mail}
    password: ${sma_mailpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  mail-exchange: mailExchange
  mail-queue: mailQueue