server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      username: mongoata
      password: root
      database: sma_userservice
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  jpa:
    hibernate:
      ddl-auto: update

feign:
  url: http://localhost:9090

jwt:
  secretKey: ${ssa_secretkey}
  issuer: ${ssa_issuer}
  audience: ${ssa_audience}

rabbitmq:
  #EXCHANGE
  user-exchange: userExchange
  #PRODUCER
  elastic-save-binding-key: elasticSaveBindingKey
  elastic-save-queue: elasticSaveQueue
  #CONSUMER
  register-queue: registerQueue
  activate-queue: activateQueue

redis:
  host: localhost
  port: 6379